:title: Known Issues, Limitations, and Assumptions
:type: using
:status: published
:parent: Replication
:summary: Known issues, limitations, and assumptions.
:order: 05

== {title}

Replication is still at an early stage in its lifecycle, so there are a few details that
the user should be aware of.

=== Federation and Replication
When mixing replication and federation there is the chance that duplicate results will appear in search results. It is recommended
that systems do not setup replication to systems they are also federated with.

=== Fanout Proxies

Replicating from a ${platform} that is configured as a http://codice.org/ddf/documentation.html#_configuring_for_a_fanout_proxy[Fanout Proxy]
will result in the replication of records from sources configured in that ${platform}.

Replicating to a ${platform} that is configured as a http://codice.org/ddf/documentation.html#_configuring_for_a_fanout_proxy[Fanout Proxy]
will result in the replication of records only to the fanout and not its sources.

=== Connected Sources

Replicating from a ${platform} that is configured with http://codice.org/ddf/documentation.html#_connected_sources[Connected Sources] will
result in the replication of records from the Connected Sources in addition to any local records.

=== Derived Resources

Derived resources, from products such as NITFs, will not be replicated. New derived resources will,
however, be generated by the receiving ${platform}.
