:title: Installing
:type: using
:status: published
:parent: Replication
:summary: Instructions for installing replication.
:order: 02

== {title}

Replication is not installed by default with a standard installation. There are several installation options available.

=== Installation When Replication _*Is*_ Included In Distribution
==== Installing Via Feature
An administrator
can install the *replication* feature by following these steps:

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Locate the *replication* feature.
. Select the *Install* arrow for the *replication* feature.
. The status will change from *Uninstalled* to *Installed*.

=== Installation When Replication _*Not*_ Included In Distribution
[NOTE]
For this scenario first copy the `replication.policy` file into the `<ddf-home>/security/` directory and restart ths system.



==== Installing Via Kar Command

On an already installed system run: `kar:install mvn:replication.distributions/replication-kar/${project.version}/kar`

==== Installing Via Hot-Deploy Directory

Copy the replication kar file into `<ddf-home>/deploy`

[NOTE]
This is the best option for systems that do not have an internet connection, because all of the dependencies for the replication feature are contained in the kar.
