version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.jodah:failsafe
    versions:
    - ">= 2.2.0.a, < 2.2.1"
  - dependency-name: net.jodah:failsafe
    versions:
    - ">= 2.3.0.a, < 2.3.1"
  - dependency-name: org.asciidoctor:asciidoctor-maven-plugin
    versions:
    - "> 1.5.6"
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - ">= 2.1.7.a, < 2.1.8"
  - dependency-name: org.springframework.data:spring-data-solr
    versions:
    - ">= 4.0.10.a, < 4.0.11"
  - dependency-name: org.testcontainers:testcontainers
    versions:
    - 1.15.1
    - 1.15.2
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
  - dependency-name: org.mariadb.jdbc:mariadb-java-client
    versions:
    - 2.7.1
