{
 "title": "Replication",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(replication_transfer_success_items_total, source)"
   }
  ]
 },
 "panels": [
  {
   "title": "Item Throughput per Minute",
   "type": "graph",
   "description": "The amount of items, in metadata and resources, passing through the system per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(replication_transfer_success_items_total{source =~ \"$source\"}[30s]) * 100",
     "legendFormat": "{{action}} Throughput"
    }
   ]
  },
  {
   "title": "Transfers",
   "type": "graph",
   "description": "The amount of items, in pairs of resources and metadata, transferred between a source and destination node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "replication_transfer_success_items_total{source =~ \"$source\"}",
     "legendFormat": "Items {{action}}D from {{source}} to {{destination}}"
    },
    {
     "expr": "replication_transfer_fail_items_total{source =~ \"$source\"}",
     "legendFormat": "Failed {{action}}S from {{source}} to {{destination}}"
    }
   ]
  },
  {
   "title": "Bytes Transferred",
   "type": "graph",
   "description": "The total amount of bytes transferred between a source and destination site.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "replication_transfer_metadata_bytes_total{source =~ \"$source\", action != \"DELETE\"}",
     "legendFormat": "Metadata Bytes {{action}}D"
    },
    {
     "expr": "replication_transfer_resource_bytes_total{source =~ \"$source\", action != \"DELETE\"}",
     "legendFormat": "Resource Bytes {{action}}D"
    }
   ]
  }
 ]
}