:title: Known Issues, Limitations, and Assumptions for Replication
:type: configuration
:status: published
:parent: Replication
:summary: Known issues, limitations, and assumptions.
:order: 25

== {title}

Replication is still at an early stage in its lifecycle, so there are a few details that
the user should be aware of.

=== Federation and Replication
When mixing replication and federation there is the chance that duplicate results will appear in search results. It is recommended
that systems do not setup replication to systems they are also federated with.

=== Fanout Proxies

Replicating from a ${branding} that is configured as a Fanout Proxy
will result in the replication of records from sources configured in that ${branding}.

Replicating to a ${branding} that is configured as a Fanout Proxy
will result in the replication of records only to the fanout and not its sources.

=== Connected Sources

Replicating from a ${branding} that is configured with Connected Sources will
result in the replication of records from the Connected Sources in addition to any local records.

=== Derived Resources

Derived resources, from products such as NITFs, will not be replicated. New derived resources will,
however, be generated by the receiving ${branding}.

=== Confluence Sources

Metadata received from a Confluence source cannot be replicated. This is because Confluence Metadata
is generated when the source is queried and contains certain information which cannot be persisted on
a ${branding}.

[NOTE]
Any metadata that is generated upon querying a source, similar to how Confluence metadata is generated,
cannot be replicated either.
