:title: Installing Replication
:type: configuration
:status: published
:parent: Replication
:summary: Instructions for installing replication.
:order: 05

== {title}

Replication is not installed by default with a standard installation. There are several installation options available.

=== Installation When Replication _*Is*_ Included In Distribution
==== Installing Via Admin Console
An administrator
can install the *replication* feature by following these steps:

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Locate the *replication* feature.
. Select the *Install* arrow for the *replication* feature.
. The status will change from *Uninstalled* to *Installed*.

=== Installation When Replication _*Not*_ Included In Distribution
[NOTE]
For this scenario first copy the `replication.policy` file into the `<${branding}-home>/security/` directory and restart the system.



==== Installing Via Hot-Deploy Directory

Copy the replication kar file into `<${branding}-home>/deploy`

[NOTE]
This is the best option for systems that do not have an internet connection, because all of the dependencies for the replication feature are contained in the kar.
