:title: Configuring Replication
:type: configuration
:status: published
:parent: Replication
:summary: Instructions for configuring replication.
:order: 15

== {title}

Replication must be configured before running.
The following sections describe the console commands that are provided for configuration.

[TIP]
====
Details about these commands can also be viewed from the ${command-console} using the `--help` option.
====

=== Adding a Replication Configuration

The preferred method of configuring replication is through the replication UI found at https://<host>:<port>/admin/replication

Configuration can still be created and managed via the commandline as detailed below.

To add a new replication configuration, use the `replication:config-add` command. It has this syntax:`

`replication:config-add --cql "<query-filter>" --direction <PUSH|BOTH> -t <METACARD|RESOURCE> --destination "<URL>" --source "<URL>" "<name>"`

For example, the following command will add a replication configuration with the name "bostonCards" that
will PUSH any local METACARDs with the word "Boston" in the title, to a remote ${branding} with the URL
"https://hostname:7777".

`replication:config-add --destination "https://hostname:7777" --cql "title like 'Boston'" --replicationType METACARD --direction PUSH "bostonCards"`

The `replicationType` option can have a value of `METACARD` or `RESOURCE`. Setting the value to `METACARD`
will replicate only the metacards that match those filters. With this setting the ${branding} that receives the replicated
metacards will not be able perform actions on the resource, such as downloading or exporting.
Setting the value to `RESOURCE` will replicate both the metacards that match the filter and their associated
resources. This setting will store a copy of the resource on the receiving ${branding}, allowing users
to download and export the resource.

The `direction` option can be set to `PUSH`, `PULL`, or `BOTH`. The PULL option has been deprecated. The `PUSH` setting replicates source
records to the ${branding} at the given destination url, `PULL` replicates records from the destination ${branding} at the
given url to the source ${branding}, and `BOTH`, does PUSH and PULL.

[WARNING]
====
It is strongly recommended to only replicate to a ${branding} that has replication installed. This
will allow the replicated metadata to be saved with the "Replication Origins" tag. The origins tag
plays a role in telling replication what data it should replicate and without it data may be undesirably
replicated back to its source.
====

The `cql` field can accept any
cql query, allowing the user to add a variety of filters to a replication configuration. Here are some examples:

.CQL Query Examples
|===
|Query|Effect

|`title like 'example'`
|Replicates records with the word "example" in the title.

|`modified before 2012-09-01T12:30:00Z`
|Replicates records for which the resource was last modified before the given date.

|`DWITHIN(anyGeo, POINT (1 2) , 10, kilometers)`
|Replicates records associated with a location inside of the given point radius.

|`DWITHIN(anyGeo, LINESTRING (1 2, 3 4) , 10, kilometers)`
|Replicates records associated with a location within 10 kilometers of a line drawn between the given coordinates.

|`INTERSECTS(anyGeo, POLYGON ( (1 2, 1 3, 2 3, 2 2, 1 2 )))`
|Replicates records associated with a location within a polygon. In this case the polygon is a bounding box.

|`modified after 2012-09-01T12:30:00Z AND modified before 2014-09-01T12:30:00Z OR title like 'Presidential'`
|Replicates records for which the resource was last modified between the given dates or that have "Presidential" in the title.
|===

=== Deleting a Replication Configuration

Replication configurations can be deleted by executing the `replication:config-delete` command, which has
this syntax:

`replication:config-delete --delete-data --delete-history --force <names>`

Where <names> is replaced with the names of the configurations to delete.

The `--delete-data` option will additionally remove all local metacards and products that were
replicated by the named configuration.

[WARNING]
====
When using the `--delete-data` option, a metacard or product that matches a different replication
configuration could be deleted if multiple replication cql filters overlap each other.
====

The `--delete-history` option will remove records of runs for the named replication configuration.
Removing these records means they will no longer show up in the `replication:status` table.

The replication configuration will not be deleted if one of the above options are specified but were unable to
be performed for some reason. The `--force` option can be used in this case to force the deletion
of the replication configuration regardless of the results of the above options.

=== Viewing Replication Configurations

To view a list of all currently saved replication configurations, simply execute `replication:config-list`
in the ${command-console}.